blank_issues_enabled: true
contact_links:
    -   name: Community support
        url: https://github.com/Fred78290/afpdeck-notification-center/discussions?discussions_q=category%3ASupport
        about: Please ask and answer questions in GitHub Discussions.
    -   name: Professional support
        url: https://www.aldunelabs.com/
        about: Get in touch with Null, the company behind Bref.
    -   name: Sponsor a feature
        url: https://www.aldunelabs.com/
        about: Sponsor the development of a new feature you want to see in Bref.
